[package]
name = "consistency"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.0"
strum = { version = "0.26", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
rand_distr = "0.4"
itertools = "0.13"
either = "1.13"

[dev-dependencies]
test-generator = "0.3"

[build-dependencies]
build-deps = "0.1"
